Initial char viewer
GMBuddy/gmbuddy-web pull request #35
Opened 2016-10-06 19:13 UTC by stephenk798

2016-10-06 19:27 UTC, garrickb commented
I am getting tons of TSLINT warnings. You should fix all of these.

2016-10-06 19:32 UTC, garrickb requested changes
Lotta things that should be fixed... You can ignore some of the comments, because we are strapped for time, but at least move things out of the state that should be props.

As long as it works, we can fix it up next sprint.

2016-10-06 19:32 UTC, garrickb commented on src/character-viewer/dnd35/CharacterData.tsx
> +export interface ICharacterDetails {
You shouldn't be duplicating interfaces. This data already exists in the `character-creator/dnd35/CharacterData` file. Just move it out of that folder into a more general folder called character-data or something, and then import it when you need it.

2016-10-06 19:32 UTC, garrickb commented on src/character-viewer/dnd35/CharacterData.tsx
> +export interface ICharacterStats {
Same here, this data is already defined in the program. So move it out of where it's already being used into a more generalized area.

2016-10-06 19:32 UTC, garrickb commented on src/character-viewer/dnd35/CharacterData.tsx
> +export interface ICharacterData {
This should look like: 

```
export interface ICharacterData {
    details: ICharacterDetails;
    stats: ICharacterStats;
}
```

and is already defined in the `character-creator/dnd35/CharacterData` file.

2016-10-06 19:32 UTC, garrickb commented on src/character-viewer/dnd35/components/CharacterView.tsx
> +const SKILLS = [
I realize it's hard to use data that doesn't exist yet, since we don't have the skill panel in the character creator, but this should really be structured in an interface somehow:

```
export interface ICharacterStat {
    name: string;
    ability: string;
    untrained: boolean;
}

export interface ICharacrterStats {
    stat: ICharacterStat[];
}
```

2016-10-06 19:32 UTC, garrickb commented on src/character-viewer/dnd35/components/CharacterView.tsx
> +		const DETAILS_DOM = Object.keys(this.props.data.details).map((key) =>{
All of these DOM things should probably be loaded in as components. Since this view page is pretty large and is display a lot info, it's be best to separate the logic a bit here.

2016-10-06 19:32 UTC, garrickb commented on src/character-viewer/dnd35/components/CharacterView.tsx
> +import * as React from "react";
This file should be in `character-viewer/dnd35/containers` since it's a main view, it's a container. Anything that's loaded into the main view would be a component.

2016-10-06 19:32 UTC, garrickb commented on src/character-viewer/dnd35/components/CharacterView.tsx
> +		const SKILLS_HEADER = <TableHeader displaySelectAll={false}>
Align the HTML elements here.

2016-10-06 19:32 UTC, garrickb commented on src/character-creator/containers/CharacterCreator.tsx
> +//THIS ONE STEVE
wot

2016-10-06 19:32 UTC, garrickb commented on src/character-viewer/containers/CharacterViewer.tsx
> +	gameType; string;
`gameType` should be a stored in props. Normally only things that deal with changing how things are displayed visually are stored in the state.

2016-10-06 19:32 UTC, garrickb commented on src/character-viewer/containers/DnD35CharacterViewer.tsx
> +    dnd35data: any;
Should be in props.

2016-10-06 19:32 UTC, garrickb commented on src/character-viewer/containers/DnD35CharacterViewer.tsx
> +				{steps}
You don't need to store this in a variable and then put it into the DOM. You can just replace `{steps}` with `CharacterViewDnD35 gametype="DnD35" data={this.state.data}/>`

But keep in mind that the data should be stored in props.

2016-10-06 19:32 UTC, garrickb commented on src/character-viewer/containers/DnD35CharacterViewer.tsx
> +export default DnD35CharacterViewer;
add new line at end of file.

2016-10-06 19:32 UTC, garrickb commented on src/character-viewer/dnd35/components/CharacterView.tsx
> +				<TableRow key={key} hoverable={true}>
Align HTML elements.

2016-10-06 19:32 UTC, garrickb commented on src/character-viewer/dnd35/components/CharacterView.tsx
> +							<Table selectable={false} className="statTable">
Align HTML elements.

2016-10-06 19:32 UTC, garrickb commented on src/character-viewer/dnd35/components/CharacterView.tsx
> +        this.setState({slideIndex: value, modifiers: this.state.modifiers});
you don't need to have ` modifiers: this.state.modifiers` in here.

2016-10-25 23:46 UTC, garrickb commented on src/character-creator/dnd35/components/CharacterDetails.tsx
> +const DEITIES = [
wow who's the dummy that misspelled that?

2016-10-26 00:06 UTC, garrickb requested changes
Mostly styling concerns. The comments about making new components doesn't really have to happen, just a thought for the future of the codebase.

2016-10-26 00:06 UTC, garrickb commented on src/character-viewer/containers/CharacterViewer.tsx
> +        let currentCharacter = <DnD35CharacterViewer
Why not just pass the whole `data` object instead of breaking it up?

2016-10-26 00:06 UTC, garrickb commented on src/character-viewer/containers/DnD35CharacterViewer.tsx
> +    constructor() {
Remove this constructor. It's doing nothing afaik.

2016-10-26 00:06 UTC, garrickb commented on src/character-viewer/dnd35/components/DetailsPage.tsx
> +        let DETAILS_DOM = Object.keys(this.props.details).map((key) => {
Rename variable just to be `details` or something like that. Title should be caps only if it's `const`.

2016-10-26 00:06 UTC, garrickb commented on src/character-viewer/dnd35/components/ItemsPage.tsx
> +import * as React from "react";
I think that this whole page should be moved into it's own component since this is essentially duplicated code from the character creator, no? You'll just need a flag to hide the add item button if the user shouldn't be able to edit the sheet.

2016-10-26 00:06 UTC, garrickb commented on src/character-viewer/dnd35/components/SkillsPage.tsx
> +        SKILLS.sort((n1, n2) => {
why

2016-10-26 00:06 UTC, garrickb commented on src/character-viewer/dnd35/components/SkillsPage.tsx
> +        SKILLS.sort((n1, n2) => {
you don't need to sort these every time a component is rendered differently. that is just super inefficient and not necessary.

2016-10-26 00:06 UTC, garrickb commented on src/character-viewer/dnd35/containers/CharacterView.tsx
> +    import SwipeableViews from "react-swipeable-views";
Remove extra tab

2016-10-26 00:06 UTC, garrickb commented on src/character-viewer/dnd35/containers/CharacterView.tsx
> +    }
new line after this

2016-10-26 00:06 UTC, garrickb commented on src/character-viewer/dnd35/styles/detailsOverview.scss
> +    text-align: center;
All other lines need to be on the same level as this.

2016-10-26 00:06 UTC, garrickb commented on src/character-viewer/dnd35/styles/detailsOverview.scss
> +}
New line at end of file pls

2016-10-26 00:06 UTC, garrickb commented on src/character-viewer/dnd35/styles/detailsOverview.scss
> +.detailsOverview{
spaces between class name and `{`.

2016-10-26 00:06 UTC, garrickb commented on src/character-viewer/dnd35/styles/statsOverview.scss
> +							vertical-align:middle;
Space after `:`.

`vertical-align: middle;`

2016-10-26 00:06 UTC, garrickb commented on src/character-viewer/dnd35/styles/statsOverview.scss
> +							vertical-align:middle;
Space after `:`

2016-10-26 00:06 UTC, garrickb commented on src/character-viewer/dnd35/styles/statsOverview.scss
> +}
New line at end of file

2016-10-26 00:06 UTC, garrickb commented on src/character-viewer/dnd35/styles/detailsOverview.scss
> +			flex-basis: 49%;
Why not have a class that encompasses both of the 49% classes?

2016-10-26 00:06 UTC, garrickb commented on src/character-viewer/dnd35/styles/detailsOverview.scss
> +			flex-basis: 15%;
Have one class that encompasses all 15% classes.

2016-10-26 00:06 UTC, garrickb commented on src/character-viewer/dnd35/styles/detailsOverview.scss
> +			flex-basis: 8%;
Have one class that encompasses all 8% classes.

2016-10-26 23:10 UTC, stephenk798 commented on src/character-viewer/containers/CharacterViewer.tsx
> +        let currentCharacter = <DnD35CharacterViewer
how? DnD35CharacterViewer expects an ICharacterData to be passed to it

2016-10-26 23:12 UTC, stephenk798 commented on src/character-viewer/dnd35/components/ItemsPage.tsx
> +import * as React from "react";
I'm not entirely sure what you mean, its already its own component. and It partially is, but some different scss will be happening, especially with layouts and stuff. Just right now its pretty bland cuz I haven't overhauled the pretty of it yet

2016-10-26 23:13 UTC, stephenk798 commented on src/character-viewer/dnd35/styles/detailsOverview.scss
> +			flex-basis: 49%;
Ignoring comment, discussed in slack.

2016-10-26 23:13 UTC, stephenk798 commented on src/character-viewer/dnd35/styles/detailsOverview.scss
> +			flex-basis: 8%;
Ignoring comment, discussed in slack.

2016-10-26 23:13 UTC, stephenk798 commented on src/character-viewer/dnd35/styles/detailsOverview.scss
> +			flex-basis: 15%;
Ignoring comment, discussed in slack.

2016-10-26 23:16 UTC, stephenk798 commented on src/character-viewer/dnd35/components/SkillsPage.tsx
> +        SKILLS.sort((n1, n2) => {
me being a lazy programmer and not knowing what skills will be added or if wanted in alphabetical order. is fixed.

2016-10-30 17:02 UTC, garrickb commented on src/character-viewer/dnd35/components/ItemsPage.tsx
> +import * as React from "react";
I meant something like a reuseable component for dnd35. maybe in the future we can have a common components folder for things like displaying items.

2016-10-30 17:09 UTC, merged